# Generated by Django 3.0.7 on 2020-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200820_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
